### PR TITLE
Added java code for Next Greater Element

### PR DESCRIPTION
**Pull request by Yuktikashyap**

### CODE REVIEW

**Comment by TecHAyusH6476** [comment]
@Yuktikashyap Make sure to create a issue to get verified for HackToberFest 
Add Valid description

**Comment by Yuktikashyap** [comment]
Hello

In my profile page of hacktoberfest it is showing that ur repo is excluded
from Hacktoberfest
So is it really excluded or am i making some mistake ?

[image: image.png]

**Comment by TecHAyusH6476** [comment]
@Yuktikashyap I dont think so, few contributors have got PR increased on their Profile
You should pass description + create a issue 
This should work fine !!

**Comment by TecHAyusH6476** [comment]
If you still face same issue so just let me know so I will mark the same on ReadMe 
Thanks

**Pull request merged**
