### PR TITLE
Added bubble sort in c++ lang

### PR DESCRIPTION
**Pull request by jhaakshita27**
Please accept the pr : )

### CODE REVIEW

**Comment by TecHAyusH6476** [comment]
@jhaakshita27 Create a issue for the PR , higher chance for Hacktober Maintainers to add PR count

**Comment by jhaakshita27** [comment]
> @jhaakshita27 Create a issue for the PR , higher chance for Hacktober Maintainers to add PR count

Created an issue for the same
Is there something else or some other suggestion that I should follow to make my pr accepted to the repo

**Comment by jhaakshita27** [comment]
> > @jhaakshita27 Create a issue for the PR , higher chance for Hacktober Maintainers to add PR count
> 
> Created an issue for the same Is there something else or some other suggestion that I should follow to make my pr accepted to the repo

Also is there any suggestion for creating new prs here itself

**Comment by TecHAyusH6476** [comment]
@jhaakshita27 
[https://github.com/zero-to-mastery/file-io](https://github.com/zero-to-mastery/file-io)
I guess that would work fine but on safer side you should try creating PRs on other repos as well
Attached few for ref 👍

**Comment by TecHAyusH6476** [comment]
@jhaakshita27 Make sure to add proper **Description** in open source repos cuz that'll count in HacktoberFest 😄

**Pull request merged**
